name: Publish to NPM

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    env:
      INPUT_TOKEN: '' # https://github.com/JS-DevTools/npm-publish/issues/15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 15

      - run: npm install

      - run: npm run test:unit

      - run: npm run build

      - run: npm run test:production

      - uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}

      - name: Build docs
        run: npm run updateExample && npm run updateDocs

      - name: Publish docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: docs
          folder: docs
